import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "./Banner";
import Footer from "./Footer";
import Navbar from "./Navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}

      <Banner />

      {/* <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Maninder.dev</h1>
        <Form />
        <Card />
      </main> */}
      {/* <h1 className="text-3xl font-bold p-10">Hello world!</h1> */}
      {/* <Footer /> */}
    </div>
  );
}
