import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "./Card";
import Footer from "./Footer";
import Form from "./Form";
import Navbar from "./Navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Maninder.dev</h1>
        <Form />
        <Card />
      </main>

      <Footer />
    </div>
  );
}
